INSERT INTO ALIEN VALUES(101,'Mohit','dotnet');
INSERT INTO ALIEN VALUES(102,'Rishi','java');
INSERT INTO ALIEN VALUES(103,'Adit','Angular');
INSERT INTO ALIEN VALUES(104,'ANurag','java');
INSERT INTO ALIEN VALUES(105,'Anjan','C');